[theme]
primaryColor = "#7ECBEE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E8F4FA"  # fond doux pour sidebar / widgets
textColor = "#262730"
font = "sans serif"


base = "light"


[server]
headless = true
port = 8501

[client]
toolbarMode = "minimal"

